apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nslice-profile-op-chart.fullname" . }}-cluster-role
  labels:
  {{- include "nslice-profile-op-chart.labels" . | nindent 4 }}
  
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - {{ quote .Values.customResource.group }}
  resources:
  - {{ quote .Values.customResource.plural }}
  verbs:
  - get
  - list
  - watch
  - patch