apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "nslice-profile-op-chart.fullname" . }}-role
  labels:
  {{- include "nslice-profile-op-chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - {{ quote .Values.customResource.group }}
  resources:
  - {{ quote .Values.customResource.plural }}
  verbs:
  - get
  - watch
  - list
  - patch