apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nslice-profile-op-chart.fullname" . }}-read-pods-and-custom-resources
  labels:
  {{- include "nslice-profile-op-chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "nslice-profile-op-chart.fullname" . }}-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "nslice-profile-op-chart.fullname" . }}-svc-account'
  namespace: '{{ .Release.Namespace }}'