apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: network-slice-profiles.av.it.pt
spec:
  group: av.it.pt
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                network-slice: 
                  type: object
                  properties:
                    name:
                      type: string
                    profile:
                      type: string
                  required:
                    - name
                    - profile
                profile-enforcement:
                  type: object
                  properties:
                    success:
                      type: boolean
                    enforced-profile:
                      type: string
                    timestamp:
                      type: string
                    result:
                      type: object
                      additionalProperties: true
                note:
                  type: string
              required:
                - network-slice  
            status:
              type: object
  scope: Namespaced
  names:
    plural: network-slice-profiles
    singular: network-slice-profile
    kind: NetworkSliceProfile
    shortNames:
      - nsp

