kubernetesClusterDomain: cluster.local
deployment:
  image:
    repository: atnog-harbor.av.it.pt/atnog/nslice-profile-op
    tag: latest
  replicas: 1
customResource:
  group: av.it.pt
  singular: network-slice-profile
  plural: network-slice-profiles
  kind: NetworkSliceProfile
  shortNames:
    - nsp
  version: v1
pollingInterval: 10
logLevel: INFO
sliceManagerBaseUrl: http://10.16.10.74:8000
