---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nslice-op
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nslice-op-cluster-role
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
    
  # Permissions for the custom resources (CRs)
  - apiGroups: ["av.it.pt"]
    resources: ["networkslices"]
    verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nslice-op-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: nslice-op
    namespace: nslice-op 
roleRef:
  kind: ClusterRole
  name: nslice-op-cluster-role
  apiGroup: rbac.authorization.k8s.io
