---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nslice-ue-op
  namespace: nslice-ue-op
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nslice-ue-op-cluster-role
  namespace: nslice-ue-op
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "patch", "create", "update"]
    
  # Permissions for the custom resources (CRs)
  - apiGroups: ["av.it.pt"]
    resources: ["networkslice-ues"]
    verbs: ["get", "list", "watch", "patch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nslice-ue-op-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: nslice-ue-op
    namespace: nslice-ue-op 
roleRef:
  kind: ClusterRole
  name: nslice-ue-op-cluster-role
  apiGroup: rbac.authorization.k8s.io
