# -*- coding: utf-8 -*-
# @Author: Rafael Direito
# @Date:   2024-10-25 07:42:33
# @Last Modified by:   Rafael Direito
# @Last Modified time: 2025-06-21 10:40:15
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: itav-ue-op
  namespace: itav-slice-manager-client
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: itav-ue-op-cluster-role
  namespace: itav-slice-manager-client
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "patch", "create", "update"]

  # Permissions for the custom resources (CRs)
  - apiGroups: ["av.it.pt"]
    resources: ["itav-ues"]
    verbs: ["get", "list", "watch", "patch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: itav-ue-op-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: itav-ue-op
    namespace: itav-slice-manager-client
roleRef:
  kind: ClusterRole
  name: itav-ue-op-cluster-role
  apiGroup: rbac.authorization.k8s.io
