# -*- coding: utf-8 -*-
# @Author: Rafael Direito
# @Date:   2024-10-21 15:46:34
# @Last Modified by:   Rafael Direito
# @Last Modified time: 2025-06-21 17:17:13
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ include "itav-netslice-op-chart.fullname" . }}-svc-account'
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "itav-netslice-op-chart.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ include "itav-netslice-op-chart.fullname" . }}-cluster-role'
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "itav-netslice-op-chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - patch
  - create
  - update
- apiGroups:
  - av.it.pt
  resources:
  - itav-netslices
  verbs:
  - get
  - list
  - watch
  - patch
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: '{{ include "itav-netslice-op-chart.fullname" . }}-cluster-role-binding'
  labels:
  {{- include "itav-netslice-op-chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "itav-netslice-op-chart.fullname" . }}-cluster-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "itav-netslice-op-chart.fullname" . }}-svc-account'
  namespace: '{{ .Release.Namespace }}'