apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ include "nslice-op-chart.fullname" . }}-svc-account'
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "nslice-op-chart.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ include "nslice-op-chart.fullname" . }}-cluster-role'
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "nslice-op-chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - patch
  - create
  - update
- apiGroups:
  - av.it.pt
  resources:
  - networkslices
  verbs:
  - get
  - list
  - watch
  - patch
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: '{{ include "nslice-op-chart.fullname" . }}-cluster-role-binding'
  labels:
  {{- include "nslice-op-chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "nslice-op-chart.fullname" . }}-cluster-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "nslice-op-chart.fullname" . }}-svc-account'
  namespace: '{{ .Release.Namespace }}'