# -*- coding: utf-8 -*-
# @Author: Rafael Direito
# @Date:   2024-10-08 18:54:07
# @Last Modified by:   Rafael Direito
# @Last Modified time: 2025-06-21 16:51:34
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: itav-netslices.av.it.pt
spec:
  group: av.it.pt
  names:
    plural: itav-netslices
    singular: itav-netslice
    kind: ITAvNetSlice
    shortNames:
      - itav-netslice
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                itav-netslice:
                  type: object
                  properties:
                    id:
                      type: string
                    administrativeState:
                      type: string
                    operationalState:
                      type: string
                    coverageArea:
                      type: string
                    sstSnssai:
                      type: object
                      properties:
                        sst:
                          type: integer
                        sd:
                          type: string
                    dnn:
                      type: string
                    priorityLabel:
                      type: integer
                    ueMobilityLevel:
                      type: string
                    reliability:
                      type: number
                    maxPacketSize:
                      type: object
                      properties:
                        maximumSize:
                          type: integer
                    latency:
                      type: object
                      properties:
                        dl:
                          type: integer
                        ul:
                          type: integer
                    delayToleranceSupport:
                      type: string
                    deterministicCommunication:
                      type: object
                      properties:
                        dl:
                          type: object
                          properties:
                            availability:
                              type: string
                            periodicity:
                              type: integer
                        ul:
                          type: object
                          properties:
                            availability:
                              type: string
                            periodicity:
                              type: integer
                    dlThroughputPerUE:
                      type: object
                      properties:
                        guaranteedThroughput:
                          type: integer
                        maximumThroughput:
                          type: integer
                    ulThroughputPerUE:
                      type: object
                      properties:
                        guaranteedThroughput:
                          type: integer
                        maximumThroughput:
                          type: integer
                    dlThroughputPerSlice:
                      type: object
                      properties:
                        guaranteedThroughput:
                          type: integer
                        maximumThroughput:
                          type: integer
                    ulThroughputPerSlice:
                      type: object
                      properties:
                        guaranteedThroughput:
                          type: integer
                        maximumThroughput:
                          type: integer
                    termDensity:
                      type: integer
                    maxNumberOfPduSessions:
                      type: integer
                    maxNumberOfUes:
                      type: integer
                    n6Protection:
                      type: string
                itav-netslice-enforcement:
                  type: object
                  additionalProperties: true
                  properties:
                    retryOnFail:
                      type: boolean
                      description: "Indicates if the system should retry upon failure."
                      default: false
                    #    currentRetries:
                    #      type: integer
                    #      description: "The number of retries attempted so far."
                    #      default: 0
                    maxRetries:
                      type: integer
                      description: "The maximum number of retries allowed."
                      default: 0
                    waitTimeBeforeRetrying:
                      type: integer
                      description: "The time in seconds to wait before each retry."
                      default: 30
                    #    success:
                    #      type: boolean
                    #      description: "If the Network Slice enforcement was successful"
                    sliceManagerResponse:
                      type: object
                      additionalProperties: true
                      description: "Response message from the slice manager upon last attempt."
                      properties:
                        success:
                          type: boolean
                        payload:
                          type: string
                        message:
                          type: string

                #    lastOperationTimestamp:
                #      type: string
                #      format: date-time
                #      description: "Timestamp of the last operation attempt."
                #    firstOperationTimestamp:
                #      type: string
                #      format: date-time
                #      description: "Timestamp of the first operation attempt."
              required:
                - itav-netslice
