# -*- coding: utf-8 -*-
# @Author: Rafael Direito
# @Date:   2024-10-22 15:55:54
# @Last Modified by:   Rafael Direito
# @Last Modified time: 2025-06-21 10:41:03
apiVersion: av.it.pt/v1
kind: ITAvUE
metadata:
  name: itav-ue
spec:
  itav-ue:
    supi: "imsi-123456789012345"
    requestedNSSAI:
      sst: 1
      sd: "123456"
    defaultNSSAI:
      sst: 1
      sd: "123456"
    dnn: "5gasp.eu"
    pduSession:
      type: "IPv4v6"
    sessionAmbr:
      uplink: 4000000
      downlink: 4000000

  itav-ue-enforcement:
    retryOnFail: true
    maxRetries: 5
    waitTimeBeforeRetrying: 10
