apiVersion: av.it.pt/v1
kind: NetworkSliceUE
metadata:
  name: network-slice-ue
spec:
  network-slice-ue:
    supi: "imsi-123456789012345"
    requestedNSSAI:
      sst: 1
      sd: "123456"
    defaultNSSAI:
      sst: 1
      sd: "123456"
    dnn: "5gasp.eu"
    pduSession:
      type: "IPv4v6"
    sessionAmbr:
      uplink: 4000000
      downlink: 4000000

  network-slice-ue-enforcement:
    retryOnFail: true
    maxRetries: 5
    waitTimeBeforeRetrying: 10