apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networkslices.av.it.pt
spec:
  group: av.it.pt
  names:
    plural: networkslices
    singular: networkslice
    kind: NetworkSlice
    shortNames:
      - nslice
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                id:
                  type: string
                administrativeState:
                  type: string
                operationalState:
                  type: string
                coverageArea:
                  type: string
                sstSnssai:
                  type: object
                  properties:
                    sst:
                      type: integer
                    sd:
                      type: string
                dnn:
                  type: string
                priorityLabel:
                  type: integer
                ueMobilityLevel:
                  type: string
                reliability:
                  type: number
                maxPacketSize:
                  type: object
                  properties:
                    maximumSize:
                      type: integer
                latency:
                  type: object
                  properties:
                    dl:
                      type: integer
                    ul:
                      type: integer
                delayToleranceSupport:
                  type: string
                deterministicCommunication:
                  type: object
                  properties:
                    dl:
                      type: object
                      properties:
                        availability:
                          type: string
                        periodicity:
                          type: integer
                    ul:
                      type: object
                      properties:
                        availability:
                          type: string
                        periodicity:
                          type: integer
                dlThroughputPerUE:
                  type: object
                  properties:
                    guaranteedThroughput:
                      type: integer
                    maximumThroughput:
                      type: integer
                ulThroughputPerUE:
                  type: object
                  properties:
                    guaranteedThroughput:
                      type: integer
                    maximumThroughput:
                      type: integer
                dlThroughputPerSlice:
                  type: object
                  properties:
                    guaranteedThroughput:
                      type: integer
                    maximumThroughput:
                      type: integer
                ulThroughputPerSlice:
                  type: object
                  properties:
                    guaranteedThroughput:
                      type: integer
                    maximumThroughput:
                      type: integer
                termDensity:
                  type: integer
                maxNumberOfPduSessions:
                  type: integer
                maxNumberOfUes:
                  type: integer
                n6Protection:
                  type: string