apiVersion: apps/v1
kind: Deployment
metadata:
  name: nslice-profile-op-deployment
  namespace: nslice-profile-op
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nslice-profile-op
  template:
    metadata:
      labels:
        app: nslice-profile-op
    spec:
      serviceAccountName: nslice-profile-op
      containers:
        - name: nslice-profile-op-container
          image: atnog-harbor.av.it.pt/atnog/nslice-profile-op
          command: ["python", "k8s_operator.py"] 
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: SLICE_MANAGER_BASE_URL
              value: "https://webhook.site/acaa8378-bab1-49e2-8c3a-d0f3d235df91"
            - name: CR_GROUP
              value: "av.it.pt"
            - name: CR_VERSION
              value: "v1"
            - name: CR_PLURAL
              value: "network-slice-profiles"
            - name: INTERVAL
              value: "10"
      restartPolicy: Always
