# -*- coding: utf-8 -*-
# @Author: Rafael Direito
# @Date:   2024-10-09 13:39:26
# @Last Modified by:   Rafael Direito
# @Last Modified time: 2025-06-21 16:59:21
apiVersion: apps/v1
kind: Deployment
metadata:
  name: itav-netslice-op-deployment
  namespace: itav-slice-manager-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itav-netslice-op
  template:
    metadata:
      labels:
        app: itav-netslice-op
    spec:
      serviceAccountName: itav-netslice-op
      containers:
        - name: itav-netslice-op-container
          image: atnog-harbor.av.it.pt/osl-custom-resources/itav-netslice-op
          command: ["python", "k8s_operator.py"]
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: SLICE_MANAGER_BASE_URL
              value: "http://10.255.28.141:8000"
            - name: SLICE_MANAGER_USERNAME
              value: "admin"
            - name: SLICE_MANAGER_PASSWORD
              value: "password"
            - name: CR_GROUP
              value: "av.it.pt"
            - name: CR_VERSION
              value: "v1"
            - name: CR_PLURAL
              value: "itav-netslices"
      restartPolicy: Always
