# -*- coding: utf-8 -*-
# @Author: Rafael Direito
# @Date:   2024-10-25 10:32:58
# @Last Modified by:   Rafael Direito
# @Last Modified time: 2025-06-21 10:31:58
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ include "itav-ue-op-chart.fullname" . }}-svc-account'
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "itav-ue-op-chart.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ include "itav-ue-op-chart.fullname" . }}-cluster-role'
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "itav-ue-op-chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - patch
  - create
  - update
- apiGroups:
  - {{ .Values.customResource.group }}
  resources:
  - {{ .Values.customResource.plural }}
  verbs:
  - get
  - list
  - watch
  - patch
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: '{{ include "itav-ue-op-chart.fullname" . }}-cluster-role-binding'
  labels:
  {{- include "itav-ue-op-chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "itav-ue-op-chart.fullname" . }}-cluster-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "itav-ue-op-chart.fullname" . }}-svc-account'
  namespace: '{{ .Release.Namespace }}'